/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fireflysource_jni_example_JniExample */

#ifndef _Included_com_fireflysource_jni_example_JniExample
#define _Included_com_fireflysource_jni_example_JniExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fireflysource_jni_example_JniExample
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fireflysource_jni_example_JniExample_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
